---
engines:
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.bash"
  - "**.sh"
  - "**.md"
exclude_paths:
  - release/
  - build/
  - tests/assert.sh
